#!/usr/bin/env bash
SCRIPT_DIR=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

PROG=$(readlink -f ${BASH_SOURCE[0]})

source $SCRIPT_DIR/common.sh

#This script is used to test Webdanica datamodel.

#It requires three arguments
# * numberofseedstoingest - e.g. 100000 (this will generate and insert 100K autogenerated seeds)
# * criteriaresultsdir - a folder with existing criteriaresults
# * criteriaresultmultiples - the amount of times to process the contents of this criteriaresultsdir folder

$JAVA_HOME/bin/java $OPTS1 $OPTS2 $OPTS3 -cp "$CLASSPATH" dk.kb.webdanica.core.tools.LoadTest $1 $2 $3
